- type: replace
  path: /releases?/name=minio?
  value:
    name: minio
    version: 2020-09-08T23-05-18Z
    url: https://bosh.io/d/github.com/minio/minio-boshrelease?v=2020-09-08T23-05-18Z
    sha1: a5e6e72254eecdf0915aaefe3764e8054e696242
