- type: replace
  path: /releases?/name=minio?
  value:
    name: minio
    version: 2022-02-12T00-51-25Z
    url: https://bosh.io/d/github.com/minio/minio-boshrelease?v=2022-02-12T00-51-25Z
    sha1: 52aedcee349cc0f0c887e4542d3b1a23d0aaa13d
