- type: replace
  path: /releases?/name=minio?
  value:
    name: minio
    version: 2021-08-20T18-32-01Z
    url: https://bosh.io/d/github.com/minio/minio-boshrelease?v=2021-08-20T18-32-01Z
    sha1: dd87f6335184174760fa79f241ec75e5f91a0de7
