- type: replace
  path: /releases?/name=minio?
  value:
    name: minio
    version: 2020-09-02T18-19-50Z
    url: https://bosh.io/d/github.com/minio/minio-boshrelease?v=2020-09-02T18-19-50Z
    sha1: a995c33f560013a0e44cfd381dc2ad52a85b8f42
