- type: replace
  path: /releases?/name=minio?
  value:
    name: minio
    version: 2020-12-23T02-24-12Z.1
    url: https://bosh.io/d/github.com/minio/minio-boshrelease?v=2020-12-23T02-24-12Z.1
    sha1: b901a73d1f118722ef7b98f4078e10c3a1af8741
