#!/bin/bash
set -eu

ip=$(exodus ip_address[0])
user=$(safe get secret/$GENESIS_VAULT_PREFIX/access_token:accesskey)
pass=$(safe get secret/$GENESIS_VAULT_PREFIX/access_token:secretkey)

list() {
  echo "The following addons are defined:"
  echo
  echo "  list           List out all supported addons."
  echo "  visit          Visit the Minio page instance."
  echo
}

case $GENESIS_ADDON_SCRIPT in
list)
  list
  exit 0
  ;;

visit)
  if ! command -v open >/dev/null 2>&1; then
    echo "The 'visit' addon script only works on macOS, currently."
    exit 1
  fi
  echo "Here's the credentials you'll need to sign in: "
  echo
  echo -e "  \033[1m\033[1;36m accesskey: \033[0m $user"
  echo -e "  \033[1m\033[1;36m secretkey: \033[0m $pass"
  url="http://$ip:9000"
  open $url
  exit 0
  ;;

*)
  echo "Unknown Minio Genesis Kit command. Try `list` to see what you can do."
  exit 1
  ;;

esac