#!/bin/bash
shopt -s nullglob
set -eu

# Genesis Kit `blueprint' Hook
#
# This script outputs the list of merge files needed to support the desired
# feature set selected by the environment parameter file.  As generated, it
# lists all *.yml files in the base, then all *.yml files in each detected
# feature directory, in the order the features are specified in the environment
# yml file.  If finer control is desired, add logic around the wants_kit_feature()
# function (takes a feature as a string, returns exit code 0 if present, non-
# zero exit code otherwise).


validate_features self-signed-cert provided-cert distributed

declare -a manifests
manifests+=( manifests/minio.yml )

if want_feature self-signed-cert ; then
  manifests+=( "manifests/self-signed.yml" )
fi

if ! want_feature self-signed-cert && ! want_feature provided-cert ; then
  echo >&2
  echo >&2 "You must select either 'self-signed-cert' feature, or 'provided-cert'."
  echo >&2 "Please try running `genesis new` again."
  echo >&2
  exit 1
fi

if want_feature distributed ; then
  manifests+=( "manifests/distributed.yml" )
  num_nodes=$(lookup params.num_minio_nodes)
  if (( $num_nodes < 4 || $num_nodes > 32 || $num_nodes % 2 != 0 )) ; then
    echo >&2
    echo >&2 "Invalid number of Minio nodes for HA. It must be greater than 4, less"
    echo >&2 "than 32, and evenly divisible by 2."
    echo >&2
    exit 1
  fi
fi

echo ${manifests[@]}

