#!/bin/bash

# Cloud Config checks
if [[ -n "$GENESIS_CLOUD_CONFIG" ]] ; then
  cloud_config_needs vm_type    "$(lookup params.vm_type    default)"
  cloud_config_needs network    "$(lookup params.network    minio)"
  cloud_config_needs disk_type  "$(lookup params.disk_type  minio)"
  if check_cloud_config ; then
    describe "  cloud-config [#G{OK}]"
  else
    describe "  cloud-config [#G{FAILED}]"
    exit 1
  fi
fi
