#!/bin/bash

# Cloud Config checks
ok=yes
if [[ -n "$GENESIS_CLOUD_CONFIG" ]] ; then
    cloud_config_needs vm_type    $(lookup params.vm_type    default)
    cloud_config_needs network    $(lookup params.network    minio)
    cloud_config_needs disk_type  $(lookup params.disk_type  minio)
    if check_cloud_config ; then
      describe "  cloud-config [#G{OK}]"
    else
      ok=no
    fi
fi

vault="secret/$GENESIS_VAULT_PREFIX"
domain="minio.$(lookup params.network minio).$(lookup params.env)-minio.bosh"
for cert in ssl/server; do
  if ! safe exists "$vault/$cert"; then
    describe "  ❌  $vault/$cert [#Y{MISSING}]"
    ok=no
  else
    if safe --quiet x509 validate "$vault/$cert" --for "*.$domain" >/dev/null 2>&1; then
      describe "  #G{✔}  $vault/$cert [#G{OK}]"
    else
      describe "  ❌  $vault/$cert [#R{INVALID}]"
      safe x509 validate "$vault/$cert" --for "*.$domain" 2>&1 | sed -e 's/^/      /';
      ok=no
      echo
    fi
  fi
done;

if [[ "$ok" = "yes" ]]; then
  describe "  environment files [#G{OK}]"
else
  describe "  environment files [#R{FAILED}]"
  exit 1
fi