#!/bin/bash
#shopt -s nullglob
set -eu

#
# Genesis Kit `new' Hook
#

ask_for_num_of_nodes() {
  prompt_for num_minio_nodes line \
    "How many Minio VMs would you like - between 4 and 12?" \
    -V "4-32" \
    --default "4"
  if (( $num_minio_nodes < 4 || $num_minio_nodes % 2 != 0 || $num_minio_nodes > 32 )) ; then
   ask_for_num_of_nodes
  fi
  param_entry params num_minio_nodes
}

describe "" \
  "Minio will be running on HTTPS, and as such, needs an SSL cert/key."
prompt_for ssl_cert_feature "select" \
  "Do you have an SSL certificate for Minio, or do you need a self-signed cert?" \
  -o "[provided-cert]I have my own certificate for Minio" \
  -o "[self-signed-cert]Please have Genesis create a self-signed certificate for Minio"
features+=("$ssl_cert_feature")

case "$ssl_cert_feature" in
  "provided-cert")
    prompt_for "$GENESIS_VAULT_PREFIX/ssl/server:certificate" secret-block \
      "What is the SSL certificate for Minio?"

    prompt_for "$GENESIS_VAULT_PREFIX/ssl/server:key" secret-block \
      "What is the SSL key for Minio?"
    ;;
esac


describe "" \
  "The external domain for Minio is the DNS entry users will use to access" \
  "Minio. You can specify the IP address if you don't have a DNS entry. Do" \
  "not include 'https://' in this value."
prompt_for external_domain line "External Domain or IP:" -i

describe "" \
  "Would you like to setup a distributed Minio install? This is a RAID-like" \
  "installation that requires at least 4 Minio instances that replicate data for" \
  "high-availibility and protection against data rot."
prompt_for distribute boolean ""

if [[ $distribute == "true" ]]; then
  describe "" \
    "How many instances of Minio would you like to deploy? It must be at least 4," \
    "at most 32, and evenly divisable by 2. (e.g. {4,6,8,...,32})"
  ask_for_num_of_nodes
  features+=("distributed")
else
  num_minio_nodes=1
fi

cat <<EOF >$GENESIS_ROOT/$GENESIS_ENVIRONMENT.yml
kit:
  name:    $GENESIS_KIT_NAME
  version: $GENESIS_KIT_VERSION
  features:
EOF

for f in "${features[@]}" ; do
  printf >>"$GENESIS_ROOT/$GENESIS_ENVIRONMENT.yml" -- '    - %s\n' "$f"
done

cat <<EOF >>$GENESIS_ROOT/$GENESIS_ENVIRONMENT.yml
params:
  env:   $GENESIS_ENVIRONMENT
  vault: $GENESIS_VAULT_PREFIX
  external_domain: $external_domain
  num_minio_nodes: $num_minio_nodes
  network: minio
EOF

exit 0

