#!/bin/bash
set -eu

if [[ $GENESIS_DEPLOY_RC == 0 ]]; then
  user=$(safe get secret/$GENESIS_VAULT_PREFIX/access_token:accesskey)
  pass=$(safe get secret/$GENESIS_VAULT_PREFIX/access_token:secretkey)
      echo; echo;
  describe "#M{$GENESIS_ENVIRONMENT} Minio deployed!"
      echo
      echo "For details about the deployment, run"
      echo
  describe "  #G{genesis info $GENESIS_ENVIRONMENT}"
      echo
      echo "To visit the Minio page:"
      echo
  describe "  #G{genesis do $GENESIS_ENVIRONMENT -- visit}"
      echo
      echo "To download s3, a CLI tool used to interact with Minio's S3 APIs:"
      echo
  describe "  #G{genesis do $GENESIS_ENVIRONMENT -- download-s3}"
      echo
      echo "To setup your environment variables to target this Minio instance:"
      echo
  describe "  #G{genesis do $GENESIS_ENVIRONMENT -- target}"=

  echo "Here's the credentials for your newly deployed Minio server. You can"
  echo "also locate them in the Vault at secret/$GENESIS_VAULT_PREFIX/access_token"
  echo
  echo
  echo -e "  \033[1m\033[1;36m accesskey: \033[0m $user"
  echo -e "  \033[1m\033[1;36m secretkey: \033[0m $pass"
  echo
fi
