jobs:
- name: minio-release
  public: true
  serial: true
  serial_groups: [bosh-release]
  plan:
    - do:
      - in_parallel:
        - { get: git, trigger: false, passed: [spec-tests] }
        - { get: git-ci, trigger: false }
        - get: bosh-release-minio
          trigger: true
          params:
            tarball: false
      - task: update-bosh-release
        file: git-ci/ci/tasks/update-bosh-release/task.yml
        input_mapping:
          bosh-release: bosh-release-minio
        params:
          OPS_FILE_PATH: manifests/releases/minio.yml
          RELEASE_NAME: minio
          BRANCH: (( grab meta.github.branch ))
      - put: git
        params:
          merge: true
          repository: pushme