#!/bin/bash
set -eu

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

cleanup() {
	for deployment in "$@"; do
		echo "> deleting ${deployment}"
		$BOSH -n -d "${deployment}" delete-deployment

		for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
			echo "  - removing disk $disk"
			$BOSH -n delete-disk "$disk"
		done
	done
}

header "Validating BOSH_* environment variables..."
set | grep BOSH_ || true

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."
cleanup ci-baseline-minio
safe rm -rf secret/genesis-ci/minio
safe cp -rf secret/genesis-ci/static/minio secret/genesis-ci/minio/ci/baseline
safe cp -rf secret/genesis-ci/static/minio secret/genesis-ci/minio/ci/proto

header "Deploying BASELINE environment to verify functionality..."
genesis add-secrets ci-baseline --vault da-vault
cat ci-baseline.yml
pwd
ls
cat dev/kit.yml
genesis -v
genesis deploy -y ci-baseline
$BOSH -d ci-baseline-minio instances --ps
header "Validating BASELINE minio..."
bosh -d ci-baseline-minio vms
IP=$($BOSH -d ci-baseline-minio vms --json | jq -r '.Tables[0].Rows[0].ips')
curl -Ik https://$IP:9000/minio/health/live
#$BOSH -d ci-baseline-minio run-errand smoke-tests
cleanup ci-baseline-minio

header "Now checking distributed variant...."
header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
cleanup ci-dist-minio
safe rm -rf secret/genesis-ci/minio
safe cp -rf secret/genesis-ci/static/minio secret/genesis-ci/minio/ci/dist
safe cp -rf secret/genesis-ci/static/minio secret/genesis-ci/minio/ci/proto

header "Deploying DISTRIBUETD environment to verify functionality..."
genesis add-secrets ci-dist --vault da-vault
cat ci-dist.yml
pwd
ls
cat dev/kit.yml
genesis -v
genesis deploy -y ci-dist
$BOSH -d ci-dist-minio instances --ps
header "Validating DISTRIBUTED minio..."
bosh -d ci-dist-minio vms
IP=$($BOSH -d ci-dist-minio vms --json | jq -r '.Tables[0].Rows[0].ips')
curl -Ik https://$IP:9000/minio/health/live
#$BOSH -d ci-dist-minio run-errand smoke-tests
cleanup ci-dist-minio